config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :spaceships, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :reservations, only: [ :create, :new ]
    resources :reviews, only: :create
  end
  resources :reservations, only: [:destroy]

  resources :users, only: [:show] do
    member do
      get 'resas', to: 'users#resas'
    end
  end

  post 'status', to: 'users#change_status'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :spaceship
  belongs_to :user

  def total_price
    zoub = spaceship.price * (Date.parse(end_date) - Date.parse(start_date)).to_i
    zoub.to_s.gsub(/(\d)(?=(\d\d\d)+(?!\d))/, "\\1 ")
  end

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :spaceship
  validates :content, length: { minimum: 20 }
end

app/models/spaceship.rb
 class Spaceship < ApplicationRecord
  include PgSearch
  belongs_to :user
  has_many :reviews, dependent: :destroy


  # CATEGORY_SHIP = ["Espace", "Air", "Aquatique", "Terrestre"]
  # validates_inclusion_of :category, in: CATEGORY_SHIP

  validates :name, uniqueness: true, presence: true
  validates :category, presence: true
  validates :planet, presence: true

  has_many :reservations, :dependent => :destroy

  mount_uploader :photo, PhotoUploader




  pg_search_scope :search_by_category_and_planet,
  against: [:category, :planet],
  using: {
    tsearch: { prefix: true }
  }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :spaceships
  has_many :reservations
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  after_action :verify_authorized, except: :index, unless: :devise_controller?
  after_action :verify_policy_scoped, only: :index, unless: :devise_controller?

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]
  after_action :verify_authorized, except: :home
  after_action :verify_policy_scoped, except: :home

  def home
    @spaceships = Spaceship.all
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  def new
    @reservation = Reservation.new
  end

  def create
    @reservation = Reservation.new(reservation_params)
    authorize @reservation
    @spaceship = Spaceship.find(params[:spaceship_id])
    @reservation.spaceship = @spaceship
    @reservation.user = current_user
    @spaceship.available = "en attente"
    @spaceship.save
    if @reservation.save
      redirect_to resas_user_path(current_user)
    else
      redirect_to spaceship_path(@spaceship)
    end

  end

  def destroy
    @reservation = Reservation.find(params[:id])
    authorize @reservation
    @spaceship = @reservation.spaceship
    @spaceship.available = "available"
    @spaceship.save
    @reservation.destroy
    redirect_to resas_user_path(@reservation.user)

  end

  def reservation_params
    params.require(:reservation).permit(:start_date, :end_date)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @review = Review.new
  end


  def create
     @spaceship = Spaceship.find(params[:spaceship_id])
     @review = Review.new(review_params)
     authorize @review
     @review.spaceship = @spaceship
     if @review.save
       respond_to do |format|
         format.html { redirect_to spaceship_path(@spaceship) }
         format.js  # <-- will render `app/views/reviews/create.js.erb`
       end
     else
       respond_to do |format|
         format.html { render 'spaceships/show' }
         format.js  # <-- idem
       end
     end

   end

   private

   def review_params
     params.require(:review).permit(:content)
   end
end

app/controllers/spaceships_controller.rb
class SpaceshipsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_spaceship, only: [:show, :edit, :update, :destroy]




  def index

    if params[:planet].present?
      @spaceships_all = Spaceship.search_by_category_and_planet(params[:planet])
    elsif params[:category].present?
      @spaceships_all = Spaceship.search_by_category_and_planet(params[:category])
    elsif params[:seats].present?
      @spaceships_all = Spaceship.where("#{:seats} >= #{params[:seats]}")
    elsif params[:star_date].present?
      @spaceships_all = Reservation.search_by_category_and_planet(params[:star_date])
    elsif params[:end_date].present?
      @spaceships_all = Reservation.search_by_category_and_planet(params[:end_date])
    else
      @spaceships_all = Spaceship.all
    end


    if params[:planet].present? && params[:category].present?
      @spaceships_all = Spaceship.where("planet = ? and category = ?", "#{params[:planet]}", "#{params[:category]}")
    elsif params[:category].present? && params[:seats].present?
      @spaceships_all = Spaceship.where("category = ? and seats >= ?", "#{params[:category]}", "#{params[:seats]}")
    elsif params[:planet].present? && params[:seats].present?
      @spaceships_all = Spaceship.where("planet = ? and seats >= ?", "#{params[:planet]}", "#{params[:seats]}")
    elsif params[:planet].present? && params[:category].present? && params[:seats].present?
      @spaceships_all = Spaceship.where("planet = ? and category = ? and seats >= ?", "#{params[:planet]}", "#{params[:category]}", "#{params[:seats]}")
    end

    @spaceships = policy_scope(Spaceship)
    # pas de authorize et policy_scope volontaires
    # Likewise, Pundit also adds verify_policy_scoped to your controller.
    # This will raise an exception similar to verify_authorized.
    # However, it tracks if policy_scope is used instead of authorize.
    # This is mostly useful for controller actions like index which find collections with a scope and don't authorize individual instances.

  end


  def show
    @reservation = Reservation.new
    @review = Review.new
   # Optionnel car réalisé dans la méthode private plus bas
   # @spaceship = Spaceship.find(params[:id])
  end

  def new
    @spaceship = Spaceship.new
    authorize @spaceship
  end

  def edit
    @spaceship = Spaceship.new
    authorize @spaceship
    @spaceship = Spaceship.find(params[:id])
  end


  def create
    @spaceship = Spaceship.new(spaceship_params)
    authorize @spaceship
    @spaceship.user = current_user
    @spaceship.save
    if @spaceship.save
      redirect_to spaceship_path(@spaceship)
    else
      render :new
    end
  end

  def edit
    @spaceship = Spaceship.find(params[:id])
  end

  def update
    @spaceship = Spaceship.find(params[:id])
    authorize @spaceship
    if @spaceship.update(spaceship_params)
      redirect_to spaceship_path(@spaceship)
    else
      render :new
    end
  end


  def destroy
    @spaceship = Spaceship.find(params[:id])
    @user = current_user
    @spaceship.destroy
    redirect_to user_path(@user)
  end

  private

    def spaceship_params
      params.require(:spaceship).permit(:name, :category, :price, :seats, :constructor, :weapons, :maxspeed, :planet, :user_id, :photo)
    end

    def set_spaceship
      @spaceship = Spaceship.find(params[:id])
      authorize @spaceship
    end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    authorize @user
  end

  def spaceship_params
    params.require(:user).permit(:email)
  end

  def resas
    @user = User.find(params[:id])
    @reservations ||= @user.reservations.order(updated_at: :desc)
    authorize @user
  end

  def change_status
    @spaceship = Spaceship.find(params[:spaceship_id])
    @spaceship.available = params[:new_availability]
    @spaceship.save
    redirect_to user_path(current_user)
    skip_authorization
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Help me, Obi-Wan Kenobi. You’re my only hope</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= yield(:after_js) %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container header" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url(<%= image_path('cantina.jpg') %>) ;">
  <div class="row content-header">
    <div class="title-header">
      <%= image_tag "mos-eisley-test.png", alt: "Mos Eisley picture" %>
    </div>
    <div class="search-header">
      <%= form_tag spaceships_path, class: "form-home", method: :get do %>
        <%= select_tag :planet, options_for_select(["Planète ?", "Alderaan", "Caamas", "Corellia", "Coruscant", "Dagobah", "Elom", "Hoth", "Mustafar", "Kamino", "Ryloth", "Tatooine", "Zonama", "Sekot" ]), class: "item-form-header" %>

        <%= date_field_tag :start_date, nil, class: "item-form-header" %>
        <%= date_field_tag :end_date, nil, class: "item-form-header" %>
        <%= submit_tag 'Rechercher', class: "item-form-header btn btn-primary", id: "hover-sound", data: { sound_url: asset_path('laser-saber.mp3')} %>
      <% end %>
    </div>
  </div>
</div>


  <div class="content-banner-cards">
    <div class="title-cards text-center">
      <span id="banner-typed-text"></span>
    </div>
  </div>

    <div class="cards">
      <div class="row">
      <% @spaceships.last(4).reverse.each do |spaceship| %>
      <div class="col-xs-12 col-md-3">
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= image_path spaceship.photo,  height: 300, width: 400, crop: :fill %>);">
<!--           <div class="card-category"><%= spaceship.category %></div> -->
          <div class="card-description">
            <h2><%= spaceship.name %></h2>
            <p>Propriétaire : <%= spaceship.user.email[/(.*@)/].chomp("@") %></p>
          </div>
           <%= link_to "", spaceship_path(spaceship), class: 'card-link' %>
        </div>
      </div>
      <% end %>
      </div>
    </div>
  </div>


<div class="homepage_layer">
  <h2 class="homepage_layer_title">
    Explorez la galaxie
  </h2>
  <p>
    Voyagez sans contrainte, choisissez le vaisseaux de vos rêves.
  </p>
  <div class="layer_images">
    <%= image_tag "x-wing.png", style:'height: 120px'; %>
    <%= image_tag "starspace-2.png", style:'height: 120px'; %>
    <%= image_tag "ansel_hsiao_04.png", style:'height: 120px'; %>
    <%= image_tag "Star-Wars-Imperial-Assault-Carrier-Vehicle.png", style:'height: 120px'; %>
  </div>
</div>

app/views/reviews/_form.html.erb
<%= simple_form_for([ spaceship, review ], remote: true) do |form| %>
  <%= form.input :content %>
  <%= form.button :submit %>
<% end %>

app/views/reviews/_show.html.erb
<p><%= review.content %></p>

app/views/reviews/create.js.erb
// Here you generate *JavaScript* that would be executed in the browser
// On veut ajouter une review
// On veut cleaner le formulaire (l'input)

<% if @review.errors.any? %>
  const newReviewForm = document.getElementById('new_review');
  newReviewForm.innerHTML = "<%= j render 'reviews/form', spaceship: @spaceship, review: @review %>";
<% else %>
  const newReviewForm = document.getElementById('new_review');
  const reviews = document.getElementById('reviews');
  reviews.insertAdjacentHTML("beforeend", "<%= j render 'reviews/show', review: @review %>");
  newReviewForm.innerHTML = "<%= j render 'reviews/form', spaceship: @spaceship, review: Review.new %>";
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fa fa-instagram"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
  </div>
  <div class="footer-copyright">
    Une plateforme conçue avec <i class="fa fa-space-shuttle"></i> sur Tatooine
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path do %>
    <%= image_tag "logo2-de-ouf.gif", class: "navbar-wagon-brand"%>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Mon hangar", user_path(current_user), class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Ajouter un vaisseau", new_spaceship_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Tous les vaisseaux", spaceships_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "avatar_default.png", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out logout"></i>  <%= t(".sign_out", default: "Se déconnecter") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
    <%= link_to t(".sign_in", default: "Se connecter"),new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>


    <%= link_to t(".sign_up", default: "S'enregistrer"),new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>

  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/spaceships/edit.html.erb
<div class="container" id="container-create-spaceship">
  <div class="row">
    <h1>Modifier le vaisseau</h1>
    <div class="col-md-4 col-md-offset-4">
      <%= simple_form_for(@spaceship) do |f| %>
        <%= f.input :name, label: 'Nom de votre vaisseau', placeholder: @spaceship.name %>
        <%= f.input :category, label: 'Categorie', :collection => %w[Espace Air Aquatique Terrestre], placeholder: @spaceship.category %>
        <%= f.input :planet, label: 'Planète', :collection => %w[Alderaan Caamas Corellia Coruscant Dagobah Elom Hoth Mustafar Kamino Ryloth Tatooine Zonama Sekot], placeholder: @spaceship.planet %>
        <%= f.input :price, label: 'Prix de location /jours', placeholder: @spaceship.price %>
        <%= f.input :seats, label: 'Sièges', placeholder: @spaceship.seats %>
        <%= f.input :constructor, label: 'Marque', placeholder: @spaceship.constructor %>
        <%= f.input :weapons, label: 'Armement', placeholder: @spaceship.weapons %>
        <%= f.input :maxspeed, label: 'Vitesse max', placeholder: @spaceship.maxspeed %>
        <%= f.input :photo, label: 'Photo de votre vaisseau', placeholder: @spaceship.photo %>
        <%= f.input :photo_cache, as: :hidden %>
        <%= f.button :submit, class: 'btn btn-primary' %>
      <% end %>
      <div class="edit-ship">
        <%= link_to "Retour au hangar", user_path(@spaceship.user_id)%>
      </div>
    </div>
  </div>
</div>

app/views/spaceships/index.html.erb
<div class="container">
  <div class="content-search-page">
      <div class="row display">
        <div class="col-md-6 content-list">
          <% @spaceships_all.each do |spaceship| %>
            <%= link_to spaceship_path(spaceship) do %>
              <div class="card-index" style="background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.7)), url(<%= image_path spaceship.photo %>);">
                <div class="card-category"><%= spaceship.category %></div>
                <div class="card-description">
                  <h2><%= spaceship.name %></h2>
                   <div class="specs">
                    <p>Sièges : <%= spaceship.seats %></p>
                    <p>Planète : <%= spaceship.planet %></p>
                    <p>Prix : <%= spaceship.price %></p>

                    <% if spaceship.available == "available" %>
                      <div class="available">
                        <%= spaceship.available %>
                      </div>
                    <% elsif spaceship.available == "en attente" %>
                        <div class="pending">
                          <%= spaceship.available %>
                        </div>
                    <% else %>
                      <div class="reserved">
                        <%= spaceship.available %>
                      </div>
                  <% end %>


                   </div>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>

        <div class="col-md-6 content-search">
          <div class="search-spaceship">
            <ul class="simple_form">
              <%= form_tag spaceships_path, method: :get do %>
                <li class="li-planet">
                  <p>Planète</p>
                  <%= select_tag :planet, options_for_select(["", "Alderaan", "Caamas", "Corellia", "Coruscant", "Dagobah", "Elom", "Hoth", "Mustafar", "Kamino", "Ryloth", "Tatooine", "Zonama", "Sekot" ]), class: "planet" %>
                </li>
                <li>
                  <p>Catégorie</p>
                  <%= select_tag :category, options_for_select(["", "Espace", "Air", "Aquatique", "Terrestre"]), class: "category" %>
                </li>
                <li>
                  <p id ="seats">Combien serez-vous ?</p>
                  <%= number_field_tag :seats,
                   params[:seats], class: "seats" %>
                </li>
                <li>
                  <%= submit_tag "Rechercher", class: "btn btn-primary" %>
                  <%= link_to "Voir tous", spaceships_path, class: "btn btn-primary"%>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
  </div>
</div>

<%= content_for(:after_js) do %>
  <script>
  const searchmenu = document.querySelector(".content-search");
  function initUpdateSearch(){
    // document.addEventListener('DOMContentLoaded', (event) => {
      // event.preventDefault();
      // console.log(searchmenu);
      searchmenu.classList.remove('content-search');
      searchmenu.classList.add('content-search-active');
    };
  // }
  window.setTimeout(initUpdateSearch, 800);
  </script>
<% end %>

<!--  label_tag(:start_date, "Début : ") %> date_field(:reservations, :start_date) label_tag(:category, "Fin : ") %> date_field(:reservations, :end_date) %>
 label_tag(:seats, "Seats : ") %> number_field(:seats, in: 1..50) %>
 -->

app/views/spaceships/new.html.erb
<div class="container" id="container-create-spaceship">
  <div class="row">
    <h1>Ajouter un nouveau vaisseau</h1>
    <div class="col-md-4 col-md-offset-4">
      <%= simple_form_for(@spaceship) do |f| %>
        <%= f.input :name, label: 'Nom de votre vaisseau' %>
        <%= f.input :category, label: 'Categorie', :collection => %w[Espace Air Aquatique Terrestre] %>
        <%= f.input :planet, label: 'Planète', :collection => %w[Alderaan Caamas Corellia Coruscant Dagobah Elom Hoth Mustafar Kamino Ryloth Tatooine Zonama Sekot] %>
        <%= f.input :price, label: 'Prix de location /jours' %>
        <%= f.input :seats, label: 'Sièges' %>
        <%= f.input :constructor, label: 'Marque' %>
        <%= f.input :weapons, label: 'Armement' %>
        <%= f.input :maxspeed, label: 'Vitesse max' %>
        <%= f.input :photo, label: 'Photo de votre vaisseau' %>
        <%= f.input :photo_cache, as: :hidden %>
        <%= f.button :submit, class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/resas.html.erb
<div class="container-hangar">


  <div class="tabs">
    <%= link_to "Vos vaisseaux", user_path(@user), class: "tab" %>
    <%= link_to "Vaisseaux réservés", resas_user_path(@user), class: "tab active" %>
  </div>
  <div class="content-banner-cards">
    <div class="cards" id="cards-resas">
      <div class="row">
      <% if @user.reservations != []  %>
        <% @reservations.each_with_index do |reservation, index| %>
        <div class="col-xs-12 col-sm-6 col-md-3">
          <div class="
          card
          <% if index == 0 %>
            first
          <% end %>
          " style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= image_path reservation.spaceship.photo,  height: 300, width: 400, crop: :fill %>);">

            <div class="card-reservation">
              <h2><%= reservation.spaceship.name %></h2>
              <% if reservation.spaceship.available == "available" %>
                  <div class="delete-icon">
                    <%= link_to reservation_path(reservation), method: :delete, data: { confirm: "Delete this booking? Are you sure stupid sith?" } do %>
                    <%= image_tag 'delete.png', width: 30 %>
                    <% end %>
                  </div>
                <div class="cancelled">
                  annulé
                </div>
              <% elsif reservation.spaceship.available == "en attente" %>
                <div class="delete-icon">
                  <%= link_to reservation_path(reservation), method: :delete, data: { confirm: "Delete this booking? Are you sure stupid sith?" } do %>
                  <%= image_tag 'delete.png', width: 30 %>
                  <% end %>
                </div>
                <div class="pending">
                  <%= reservation.spaceship.available %>
                </div>
              <% else %>
                <div class="reserved">
                  accepté
                </div>
            <% end %>

              <p>Début le :<%= reservation.start_date %></p>
              <p>Fin le :<%= reservation.end_date %></p>
              <p style = "font-weight: bold">Total : <%= reservation.total_price %> crédits</p>
            </div>

          </div>


        </div>
        <% end %>
      <% else  %>
          <p style="color: ghostwhite; font-weight: lighter; color: ghostwhite; font-weight: lighter; margin: 13% 0% 100% 24%; width: 320px;"> Vous n'avez aucune réservation </p>
      <% end %>

      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container-hangar">
<!--   <h1 class="id-hangar">Vos véhicules</h1> -->

<div class="tabs">
  <%= link_to "Vos vaisseaux", user_path(@user), class: "tab active" %>
  <%= link_to "Vaisseaux réservés", resas_user_path(@user), class: "tab" %>
</div>


  <div class="content-banner-cards">
    <div class="cards" id="cards-myships">
      <div class="row">
      <% @user.spaceships.each do |spaceship| %>
      <div class="col-xs-12 col-sm-6 col-md-3">
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= image_path spaceship.photo,  height: 300, width: 400, crop: :fill %>);">
          <div class="edit-icon">
            <%= link_to edit_spaceship_path(spaceship) do  %>
              <%= image_tag 'edit.png', width: 30 %>
            <% end %>
          </div>
          <div class="delete-icon">

            <%= link_to spaceship_path(spaceship), method: :delete, remote: true, data: { confirm: "Delete this wonderful spaceship? Are you sure?" } do %>
            <%= image_tag 'delete.png', width: 30 %>
            <% end %>
          </div>

          <div class="card-description">
            <%= link_to spaceship.name, spaceship_path(spaceship) %>
            <% if spaceship.available == "available" %>
                <div class="available">
                  <%= spaceship.available %>
                </div>
              <% elsif spaceship.available == "en attente" %>
                  <div>
                    <%= link_to status_path(user_id: current_user, spaceship_id: spaceship.id, new_availability: "réservé"), method: :post do %>
                    <p>Accepter</p>
                    <% end %>
                    <%= link_to status_path(user_id: current_user, spaceship_id: spaceship.id, new_availability: "available"), method: :post do %>
                    <p>Refuser</p>
                    <% end %>
                  </div>
                  <div class="pending">
                    <%= spaceship.available %>
                  </div>
              <% else %>
                <div class="reserved">
                  <%= spaceship.available %>
                </div>
            <% end %>
          </div>

        </div>


      </div>
      <% end %>
      </div>
    </div>
  </div>
</div>